### PR TITLE
Rename sffnctx.Apex* to represent Class and Trigger

### PR DESCRIPTION
**Pull request by cwallsfdc**
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000767itYAA/view

### CODE REVIEW

**Comment by doriskwan** [comment]
I'd like the same schema changes to be reflected the tests for consistency:

[ref 1](https://github.com/forcedotcom/sf-fx-runtime-java/blob/9b395a8c08362194e6b5f157cb0dcfcd6282500e/sf-fx-runtime-java-runtime/src/test/java/com/salesforce/functions/jvm/runtime/sfjavafunction/SalesforceFunctionTest.java#L139) 

[ref 2](https://github.com/forcedotcom/sf-fx-runtime-java/blob/1b1d0c024166816a4e93eaba0406a90c3a09e909/sf-fx-runtime-java-runtime/src/test/java/com/salesforce/functions/jvm/runtime/sfjavafunction/SalesforceFunctionsProjectFunctionsScannerTest.java#L377)

**Comment by edmorley** [comment]
It's worrying that the tests didn't fail before the tests were updated?

**Comment by doriskwan** [comment]
> It's worrying that the tests didn't fail before the tests were updated?

@edmorley yeah, that's fairly interesting, since the schema update the property name value "apexClassId" I'm still continuing my deeper dive before I approve this PR 💯

**Comment by joshwlewis** [comment]
> It's worrying that the tests didn't fail before the tests were updated?

I don't think these fields were used by the runtime at all. Any functions relying on this field would probably be the part that breaks. 


@cwallsfdc are the core-side changes still scheduled for Tuesday? I think we'll need to deploy these changes on that day?

**Comment by cwallsfdc** [comment]
Yes, Tuesday.  To be more agile, could the Java and nodejs runtimes be lenient on parsing?  Ie, allow unknown properties?  I don't think Core was actually sending these values.

**Comment by edmorley** [comment]
@joshwlewis To ease coordinating the rollout, we could release everything apart from the final pack-images PR before Tuesday, giving us only the pack-images PR merge to perform on the day itself.

**Comment by doriskwan** [comment]
@edmorley @joshwlewis I've run it locally testing new changes with the `apexClassId vs apexId` and `apexClassFQN vs apexFQN`

Doesn't look like it breaks any functionality so I'll give my approval and watch out during bug bash, which I'm kind of participating in.

**Review by doriskwan — APPROVED** [review]

**Pull request merged**
